pipeline {
    agent any
    stages {
        stage("Deploy Production Environment"){
            steps{
                withCredentials([file(credentialsId: 'SSHKey', variable: 'SSHKeyPair')]) {
                     sh '''
                        ssh -i ${SSHKeyPair} ubuntu@<PROD_IP> -oStrictHostKeyChecking=no  << EOF
                        sudo apt-get update
                        git clone https://github.com/HShanks19/PublicProjectRepo
                        cd ~/PublicProjectRepo
                        docker-compose build --parallel
                        docker-compose up -d
                    '''
                }
            }
        }
    }
}
