variable "net_id_prod" {}
variable "net_id_test" {}
variable "net_id_jenk" {}
variable "ami_id" {}
variable "instance_type" {}
variable "av_zone" {}
variable "key_name" {}
variable "sec_group_id" {}
variable "subnet_group_name" {}
variable "db_password" {}